version: 2
jobs:
  test:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-27-alpha
        environment:
          TZ: Asia/Tokyo
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Print Android home
          command: echo $ANDROID_HOME
      - run:
          name: Accept licenses
          command: yes | sdkmanager --licenses || true
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - run:
          name: Decode google-services.json
          command: echo $GOOGLE_SERVICE | base64 --decode > ./app/google-services.json
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew testDebugUnitTest
      - store_test_results:
          path: app/build/test-results
  lint:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-27-alpha
        environment:
          TZ: Asia/Tokyo
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Print Android home
          command: echo $ANDROID_HOME
      - run:
          name: Accept licenses
          command: yes | sdkmanager --licenses || true
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - run:
          name: Decode google-services.json
          command: echo $GOOGLE_SERVICE | base64 --decode > ./app/google-services.json
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Run Lint
          command: ./gradlew lintDebug
      - store_artifacts:
          path: app/build/reports
          destination: reports

workflows:
  version: 2
  test_and_lint:
    jobs:
      - test
      - lint
